
- name: Unarchive a tomcat tar from tomcat website
  unarchive:
    src: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v{{ tomcatVersion }}/bin/apache-tomcat-{{ tomcatVersion }}.tar.gz
    dest: /etc/
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - tar-copy

- name: create a soft link to th tomcat folder
  file:
    src: /etc/apache-tomcat-{{ tomcatVersion }}
    dest: /etc/tomcat
    owner: root
    group: root
    state: link
  tags:
    - softlink
